name: Deploy Python App to Azure Function App

on:
  push:
    branches: ["main"]  # Triggers deployment when pushing to main branch
  workflow_dispatch:  # Allows manual execution from GitHub Actions UI

permissions:
  id-token: write # This is required for requesting the JWT
  contents: read

env:
  AZURE_FUNCTIONAPP_NAME: "therranen-portman-func"  # set this to the name of your Azure Web App
  AZURE_FUNCTIONAPP_PACKAGE_PATH: "."
  PYTHON_VERSION: "3.11"

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    environment:
      name: Development

    steps:
      # Checkout the repository
      - name: Checkout Code
        uses: actions/checkout@v4

      # Set up Python environment
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: ${{ env.PYTHON_VERSION }}  # Change if using a different Python version

      # Resolve and install dependencies
      - name: Resolve Project Dependencies Using Pip
        run: |
          cd ./AzureHttpTrigger
          python -m pip install --upgrade pip
          pip install --target="./.python_packages/lib/site-packages" -r requirements.txt
      
      - name: Zip the Azure Function Deploy folder
        run: |
          cd AzureHttpTrigger
          zip -r ../AzureHttpTrigger.zip ./*

      #- name: Resolve Project Dependencies Using Pip
      #  run: |
      #    python -m pip install --upgrade pip
      #    pip install -r requirements.txt --target=".python_packages/lib/site-packages"

      # Log in to Azure
      - name: Log in to Azure
        uses: azure/login@v1
        with:
          client-id: ${{ secrets.AZURE_CLIENT_ID }}
          tenant-id: ${{ secrets.AZURE_TENANT_ID }}
          subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}

      # Deploy to Azure
      #- name: Run Azure Functions Action
      #  uses: Azure/functions-action@v1
      #  id: fa
      #  with:
      #    app-name: ${{ env.AZURE_FUNCTIONAPP_NAME }}
      #    package: ${{ env.AZURE_FUNCTIONAPP_PACKAGE_PATH }}
      #    scm-do-build-during-deployment: true
      #    enable-oryx-build: true

      # Logout from Azure (cleanup)
      #- name: Logout from Azure
      #  run: az logout
